# Your Name or Company
title: DL Evans

# Description of your website. This is used for social sharing.
description:  Me on a website.

# A brief blurb about yourself
content: I'm DL. I work with emerging technologies and focus on IP video delivery. <br> I have a recreational interest in Bitcoin. Laser eyes and diamond hands.

# Add your social links
social:
#  - platform: github
#    url: https://github.com/davemane
#  - platform: facebook
#    url: https://facebook.com/barackobama
#  - platform: twitter
#    url: https://twitter.com/davemane
#  - platform: linkedin
#    url: https://www.linkedin.com/in/david-evans-80597a46/

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
