# Your Name or Company
title: DL Evans

# Description of your website. This is used for social sharing.
description:  My resume as a website seemed like a good idea.

# A brief blurb about yourself
content: I focus on IP delivery of video. Putting videos on people's phones is entertaining for both parties. I'm interested in new technologies and fun stuff outdoors.

# Add your social links
social:
  - platform: github
    url: https://github.com/davemane
  - platform: facebook
    url: https://facebook.com/brianmaierjr
  - platform: twitter
    url: https://twitter.com/davemane
  - platform: linkedin
    url: david-evans-80597a46

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
